# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  mssqlserver:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd1
    ports:
      - 1433:1433

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
